name: 'Skip Duplicate Actions'
description: 'Skip duplicate workflow-runs. Cancel outdated workflow-runs.'
author: fkirc
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  github_token:
    description: 'Your GitHub Access Token'
    required: true
  cancel_others:
    description: 'If true, then workflow-runs from outdated commits will be cancelled'
    required: false
    default: 'true'
  cancel_self:
    description: 'If true, then the workflow will cancel itself if a duplicate workflow-run was found'
    required: false
    default: 'true'

outputs:
  should_skip:
    description: 'true if a duplicate workflow-run was found, false otherwise. This is only relevant if cancel_self is false.'
runs:
  using: 'node12'
  main: 'dist/index.js'
