name: 'Skip Duplicate Action Runs'
description: 'This Action will skip workflows that have been successfully executed before with the exact same files.'
author: fkirc
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  github_token:
    description: 'Your GitHub Access Token, ie: {{ github.token }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
