name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token:
    description: 'secrets.GITHUB_TOKEN'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  pre: 'pre-step.js'
  pre-if: 'always()'
  main: 'check-duplicate.js'
  post: 'upload-success.js'
  post-if: 'success()'
