name: 'Skip Duplicate Actions'
description: 'Skip duplicate workflow-runs. Cancel outdated workflow-runs.'
author: fkirc
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  github_token:
    description: 'Your GitHub Access Token'
    required: true
  cancellation_enabled:
    description: 'Enable or disable the cancellation feature'
    required: false
    default: 'true'
outputs:
  should_skip:
    description: 'true if a duplicate workflow-run was found, false otherwise'
runs:
  using: 'node12'
  main: 'dist/index.js'
