on: [push, workflow_dispatch]

jobs:
  self_test:
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-action-runs@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: pwd && ls -la
